[package]
name = "pamusb-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true

udev = { version = "0.9.3", default-features = false }

toml = { version = "1.1.4", default-features = false, features = ["serde", "parse"] }
serde = { version = "1.0.229", features = ["derive"] }

fastrand = "2.5.0"

subtle = { version = "2.6.1", default-features = false }
zeroize = { version = "1.9.0", default-features = false }

wrapper-utils.workspace = true
libc = "0.2.189"
